import type {ScreenStroke,SurfaceAnnotation} from '../api';
import type {SceneViewport} from '../viewport/types';
import type {MarkupCanvas} from '../markup';
import {OperationError} from '../operations/core';
import {AnnotationHistory,type AnnotationEditor,type AnnotationMode,type AnnotationToolbarState} from './editor';
import {createAnnotationToolbar} from './toolbar';
import {validateColor,validateScreens} from './validation';

type Snapshot={strokes:ScreenStroke[];selected?:string};
export class ScreenAnnotationEditor implements AnnotationEditor {
 private readonly panel=createAnnotationToolbar(false);
 private readonly list=document.createElement('section');
 private readonly badges=document.createElement('div');
 private readonly timeline=new AnnotationHistory<Snapshot>();
 private active=false;private mode:AnnotationMode='screen';private color='#ff6b5e';private selected?:string;
 private external=document.documentElement.classList.contains('embedded-scene');private dismissed=false;private before?:Snapshot;private suspended?:{mode:AnnotationMode;selected?:string};
 constructor(private readonly viewport:SceneViewport,private readonly markup:MarkupCanvas,private readonly shell:HTMLElement,private readonly callbacks:{toast:(message:string)=>void;change:()=>void}) {
  shell.append(this.panel);this.list.className='surface-list';this.list.hidden=true;this.list.dataset.labelObstacle='';this.list.setAttribute('aria-label','标记列表');document.querySelector('#scene-panels')!.append(this.list);
  this.badges.id='surface-badges';document.querySelector('#viewer')!.append(this.badges);
  this.panel.querySelectorAll<HTMLButtonElement>('[data-surface-mode]').forEach(button=>button.addEventListener('click',()=>this.setTool(button.dataset.surfaceMode as AnnotationMode)));
  this.panel.querySelectorAll<HTMLButtonElement>('[data-surface-color]').forEach(button=>button.addEventListener('click',()=>this.setColor(button.dataset.surfaceColor!)));
  this.panel.querySelector('#surface-done')!.addEventListener('click',()=>this.exit());
  this.panel.querySelector('#surface-undo')!.addEventListener('click',()=>this.undo());this.panel.querySelector('#surface-redo')!.addEventListener('click',()=>this.redo());
  this.panel.querySelector('#surface-delete')!.addEventListener('click',()=>{if(this.selected)this.removeAnnotation('screen',this.selected);});
  this.panel.querySelector<HTMLInputElement>('#surface-name')!.addEventListener('change',event=>{if(this.selected)this.editScreen(this.selected,{label:(event.target as HTMLInputElement).value.trim()});});
  this.markup.onStrokeStart=()=>{this.before=this.snapshot();this.selected=undefined;};
  this.markup.onStrokeEnd=()=>{if(this.before){const strokes=this.markup.exportStrokes();if(strokes.length>this.before.strokes.length){this.timeline.remember(this.before);this.selected=strokes.at(-1)?.id;}this.before=undefined;}this.sync();};
  document.querySelector('#viewer')!.addEventListener('pointerdown',event=>{if(!this.active||this.mode!=='select'||!(event instanceof PointerEvent)||event.button!==0)return;const index=this.markup.hitTest(event.clientX,event.clientY);if(index!==undefined){this.select('screen',this.markup.exportStrokes()[index].id);event.preventDefault();event.stopPropagation();}},true);
  window.addEventListener('keydown',event=>{if(!this.active||event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement||document.querySelector('dialog[open]'))return;
   if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?this.redo():this.undo();}
   else if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();if(this.selected)this.removeAnnotation('screen',this.selected);}
   else if(event.key==='Escape'){event.preventDefault();this.cancel();this.exit();}
   else if(event.code==='Space'&&!event.repeat){event.preventDefault();this.setTool('select');}
   else if(event.key==='Enter'){event.preventDefault();this.finish();}
  });
  this.viewport.renderListeners.add(()=>this.renderBadges());
  new ResizeObserver(()=>this.updateLayout()).observe(this.panel);window.addEventListener('resize',()=>this.updateLayout());window.visualViewport?.addEventListener('resize',()=>this.updateLayout());window.visualViewport?.addEventListener('scroll',()=>this.updateLayout());
  this.refreshList();this.updateLayout();
 }
 get isActive():boolean{return this.active;}
 get toolbarState():AnnotationToolbarState {const stroke=this.markup.exportStrokes().find(s=>s.id===this.selected),busy=this.markup.isDrawing;return {active:this.active,mode:this.mode,color:stroke?.color??this.color,selection:stroke?{kind:'screen',id:stroke.id}:null,label:stroke?.label??'',canUndo:!!this.timeline.past.length&&!busy,canRedo:!!this.timeline.future.length&&!busy,canClose:false,closed:false,canFinishLine:false,busy,status:'屏幕画笔 · 松手成一笔，改变视角后隐藏',supportsSurface:false};}
 async enter(id?:string):Promise<void>{if(id&&!this.markup.exportStrokes().some(s=>s.id===id))throw new OperationError('INVALID_ARGUMENT','Screen annotation not found',{target:id});if(this.active){if(id)this.select('screen',id);return;}this.active=true;this.dismissed=false;this.mode=id?'select':'screen';this.selected=id;if(!document.documentElement.classList.contains('embedded-scene')){const share=document.querySelector('#share-view');if(share)this.panel.querySelector('.surface-actions')!.append(share);}this.panel.hidden=false;this.shell.classList.add('surface-mode');document.querySelector('#gesture-hint')?.classList.add('dismissed');this.sync();}
 exit():void {if(!this.active)return;this.markup.finishActive();this.active=false;this.selected=undefined;this.panel.hidden=true;this.shell.classList.remove('surface-mode');const share=this.panel.querySelector('#share-view');if(share)document.querySelector('.review-dock .dock-main')?.append(share);this.viewport.setInteractionEnabled(true);this.sync();}
 load():void{this.timeline.clear();this.selected=undefined;this.before=undefined;this.dismissed=false;this.sync();}
 finishForShare():void{this.markup.finishActive();this.sync();}
 invalidateScreenHistory():void{this.markup.cancelActive();this.timeline.clear();this.before=undefined;this.selected=undefined;this.sync();}
 suspend():void{if(!this.active)return;this.suspended={mode:this.mode,selected:this.selected};this.exit();}
 resume():void{if(!this.suspended)return;const saved=this.suspended;this.suspended=undefined;void this.enter();this.mode=saved.mode;this.selected=saved.selected;this.sync();}
 setExternalScreenMarkup(external:boolean):void{this.external=external;this.sync();}
 setTool(mode:AnnotationMode):void{if(mode==='point'||mode==='line')throw new OperationError('UNSUPPORTED','Board supports screen annotations only',{field:'mode'});if(mode===this.mode)return;this.markup.finishActive();this.mode=mode;this.selected=undefined;this.sync();}
 setColor(color:string):void{this.assertNoStroke();validateColor(color);this.color=color;if(this.selected){this.editScreen(this.selected,{color});return;}this.sync();}
 select(kind:'surface'|'screen',id:string):void{if(kind==='surface')throw new OperationError('UNSUPPORTED','Board has no surface annotations');const stroke=this.markup.exportStrokes().find(s=>s.id===id);if(!stroke)throw new OperationError('INVALID_ARGUMENT','Screen annotation not found',{target:id});this.markup.finishActive();this.selected=id;this.mode='select';this.color=stroke.color;this.sync();}
 createScreen(input:Omit<ScreenStroke,'id'>):ScreenStroke{this.assertNoStroke();const stroke={...structuredClone(input),id:crypto.randomUUID()},strokes=[...this.markup.exportStrokes(),stroke];validateScreens(strokes);this.timeline.remember(this.snapshot());this.markup.load(strokes);this.selected=stroke.id;this.sync();return structuredClone(stroke);}
 editScreen(id:string,patch:Partial<Omit<ScreenStroke,'id'>>):ScreenStroke{this.assertNoStroke();const strokes=this.markup.exportStrokes(),index=strokes.findIndex(s=>s.id===id);if(index<0)throw new OperationError('INVALID_ARGUMENT','Screen annotation not found',{target:id});const previous=JSON.stringify(strokes[index]);strokes[index]={...strokes[index],...structuredClone(patch)};validateScreens(strokes);if(JSON.stringify(strokes[index])===previous)return structuredClone(strokes[index]);this.timeline.remember(this.snapshot());this.markup.load(strokes);this.sync();return structuredClone(strokes[index]);}
 removeAnnotation(kind:'surface'|'screen',id:string):void{if(kind==='surface')throw new OperationError('UNSUPPORTED','Board has no surface annotations');this.assertNoStroke();const strokes=this.markup.exportStrokes(),index=strokes.findIndex(s=>s.id===id);if(index<0)throw new OperationError('INVALID_ARGUMENT','Screen annotation not found',{target:id});this.timeline.remember(this.snapshot());strokes.splice(index,1);this.markup.load(strokes);if(this.selected===id)this.selected=undefined;this.sync();}
 clearAnnotations(kind?:'surface'|'screen'):void{if(kind==='surface')throw new OperationError('UNSUPPORTED','Board has no surface annotations');this.assertNoStroke();if(!this.markup.hasStrokes)return;this.timeline.remember(this.snapshot());this.markup.clear();this.selected=undefined;this.sync();}
 undo():void{if(this.before)this.cancel();const previous=this.timeline.past.pop();if(!previous)return;this.timeline.future.push(this.snapshot());this.restore(previous);}
 redo():void{if(this.before)this.cancel();const next=this.timeline.future.pop();if(!next)return;this.timeline.past.push(this.snapshot());this.restore(next);}
 finish():void{this.finishForShare();}
 cancel():void{this.markup.cancelActive();if(this.before)this.restore(this.before);this.before=undefined;this.sync();}
 private assertNoStroke():void {if(this.markup.isDrawing)throw new OperationError('CONFLICT','Finish or cancel the active screen stroke first');}
 setClosed(_id:string,_closed:boolean):void{throw new OperationError('UNSUPPORTED','Board has no surface line closure');}
 surfaceAnnotations():SurfaceAnnotation[]{return [];}
 private snapshot():Snapshot{return {strokes:this.markup.exportStrokes(),selected:this.selected};}
 private restore(snapshot:Snapshot):void{this.markup.load(snapshot.strokes);this.selected=snapshot.selected;this.sync();}
 refreshList():void{this.list.replaceChildren();const strokes=this.markup.exportStrokes();if(!strokes.length){this.list.hidden=true;return;}const header=document.createElement('div');header.className='surface-list-heading';const title=document.createElement('strong');title.textContent='标记';const close=document.createElement('button');close.type='button';close.textContent='×';close.setAttribute('aria-label','收起标记列表');close.addEventListener('click',()=>{this.dismissed=true;this.updateLayout();});header.append(title,close);this.list.append(header);strokes.forEach((stroke,index)=>{const row=document.createElement('div');row.className='surface-list-row';row.classList.toggle('selected',stroke.id===this.selected);const button=document.createElement('button');button.type='button';button.setAttribute('aria-pressed',String(stroke.id===this.selected));const badge=document.createElement('i');badge.textContent=String(index+1);badge.style.setProperty('--ink',stroke.color);const label=document.createElement('span');label.textContent=stroke.label||`画笔 ${index+1}`;const kind=document.createElement('small');kind.textContent='屏幕';button.append(badge,label,kind);button.addEventListener('click',()=>void this.enter(stroke.id));row.append(button);this.list.append(row);});this.updateLayout();}
 private updateLayout():void{const viewport=window.visualViewport,height=viewport?.height??window.innerHeight;this.shell.style.setProperty('--annotation-viewport-height',`${height}px`);this.shell.style.setProperty('--annotation-keyboard-inset',`${Math.max(0,window.innerHeight-height-(viewport?.offsetTop??0))}px`);this.shell.style.setProperty('--annotation-toolbar-height',`${this.active?this.panel.offsetHeight:64}px`);this.list.hidden=this.dismissed||!this.markup.hasStrokes||(viewport?.width??window.innerWidth)<900||height<600;}
 private renderBadges():void{this.badges.replaceChildren();this.markup.exportStrokes().forEach((stroke,index)=>{const points=this.markup.displayPoints(index),point=points[Math.floor(points.length/2)];if(!point)return;const button=document.createElement('button');button.type='button';button.className='surface-badge';button.classList.toggle('selected',stroke.id===this.selected);button.style.setProperty('--ink',stroke.color);button.style.transform=`translate3d(${point[0]}px,${point[1]}px,0)`;button.textContent=stroke.label||`画笔 ${index+1}`;button.style.pointerEvents=this.active&&this.mode==='screen'?'none':'auto';button.addEventListener('click',()=>void this.enter(stroke.id));this.badges.append(button);});}
 private sync():void{const state=this.toolbarState;this.markup.setEnabled(this.active&&this.mode==='screen'&&!this.external);this.markup.setColor(this.color);this.markup.setSelection(this.active?this.markup.exportStrokes().findIndex(s=>s.id===this.selected):undefined);if(this.active)this.viewport.setInteractionEnabled(this.mode==='select');this.panel.querySelectorAll<HTMLButtonElement>('[data-surface-mode]').forEach(button=>{const on=button.dataset.surfaceMode===this.mode;button.classList.toggle('active',on);button.setAttribute('aria-pressed',String(on));});this.panel.querySelectorAll<HTMLButtonElement>('[data-surface-color]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.surfaceColor===state.color)));this.panel.querySelector<HTMLButtonElement>('#surface-undo')!.disabled=!state.canUndo;this.panel.querySelector<HTMLButtonElement>('#surface-redo')!.disabled=!state.canRedo;(this.panel.querySelector('.surface-selection') as HTMLElement).hidden=!state.selection;const input=this.panel.querySelector<HTMLInputElement>('#surface-name')!;if(document.activeElement!==input)input.value=state.label;(this.panel.querySelector('#surface-close') as HTMLElement).hidden=true;(this.panel.querySelector('#surface-end') as HTMLElement).hidden=true;this.panel.querySelector('#surface-hint')!.textContent=state.status;document.querySelector('#brush-tool')?.setAttribute('aria-pressed',String(this.active));this.refreshList();this.renderBadges();this.callbacks.change();}
}
